### ISSUE TITLE
files for chapter 9: dem_gal.7z and dem_gal.asc (Galicia DEM)

### ISSUE THREAD

**Issue by ckluss** [oscarperpinan/spacetime-vis#5]
Hi,

can somebody provide the dem_gal.7z, dem_gal.asc files?

The book-links do not work :( so I cannot go through the examples in chapter 9.

thx
Christof

http://ide.unex.es/geonetwork/srv/es/main.search?any=MDE_Galicia
http://ide.unex.es:8180/geonetwork/srv/es/resources.get?id=21&fname=dem_gal.7z&access=private

**Comment by oscarperpinan** [comment]
Hi,

Thank you for letting me know. It seems that the UNEX server is down. Anyway, I have extracted the data corresponding to the region of interest, and the corresponding files are available at the `data` folder. Besides, I have modified the code to use these files.
